# Generated by Django 5.0.6 on 2024-08-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=2)),
            ],
        ),
    ]
