# Generated by Django 5.0.6 on 2024-08-15 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_cidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="cidade",
            name="estado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cidade",
                to="core.estado",
            ),
        ),
    ]
