# Generated by Django 5.0.6 on 2024-08-22 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_cidade_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rua", models.CharField(max_length=255)),
                ("cep", models.PositiveIntegerField()),
                (
                    "cidades",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cidades",
                        to="core.cidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereco",
                "verbose_name_plural": "Ederecos",
            },
        ),
    ]
