# Generated by Django 5.0.6 on 2024-08-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_endereco"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="endereco",
            options={"verbose_name": "Endereco", "verbose_name_plural": "Enderecos"},
        ),
    ]
