# Generated by Django 5.0.6 on 2024-08-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="categoria",
            field=models.ManyToManyField(blank=True, null=True, related_name="pedido", to="core.categoria"),
        ),
    ]
