# Generated by Django 5.0.6 on 2024-08-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_pedido_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="produto",
            field=models.ManyToManyField(blank=True, null=True, related_name="produto", to="core.produto"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="categoria",
            field=models.ManyToManyField(blank=True, null=True, related_name="produto", to="core.categoria"),
        ),
    ]
