# Generated by Django 5.0.6 on 2024-08-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_pedido_produto_alter_pedido_categoria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="categoria",
        ),
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.ManyToManyField(blank=True, null=True, related_name="produto", to="core.categoria"),
        ),
    ]
