# Generated by Django 5.0.6 on 2024-08-29 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_pedido_options_produto_tamanho_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="endereco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cidade",
                to="core.endereco",
            ),
        ),
    ]
