# Generated by Django 5.0.6 on 2024-08-29 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_user_endereco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="endereco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ENDEREÇO",
                to="core.endereco",
            ),
        ),
    ]
