# Generated by Django 5.0.6 on 2024-08-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_user_endereco"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="endereco",
        ),
    ]
