# Generated by Django 5.1 on 2024-09-12 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_user_capa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="endereco",
            options={"verbose_name": "Endereço", "verbose_name_plural": "Endereços"},
        ),
        migrations.RenameField(
            model_name="endereco",
            old_name="cidades",
            new_name="cidade",
        ),
        migrations.AddField(
            model_name="endereco",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enderecos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
