# Generated by Django 5.1 on 2024-09-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_endereco_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="capa",
            new_name="foto",
        ),
        migrations.AlterField(
            model_name="pedido",
            name="produto",
            field=models.ManyToManyField(blank=True, related_name="pedidos", to="core.produto"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=models.ManyToManyField(blank=True, related_name="produto", to="core.categoria"),
        ),
    ]
