# Generated by Django 5.1 on 2024-12-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_remove_itenscompra_pedido_itenscompra_produtos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="produto",
            field=models.ManyToManyField(related_name="pedidos", to="core.produto"),
        ),
    ]
