# Generated by Django 5.1 on 2024-12-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_pedido_produto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="produto",
            field=models.ManyToManyField(blank=True, related_name="pedidos", to="core.produto"),
        ),
    ]
